# Generated by Django 2.2.3 on 2019-07-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('img_url', models.URLField()),
                ('rate', models.DecimalField(decimal_places=1, max_digits=3)),
                ('detail_url', models.URLField()),
            ],
        ),
    ]
