# Generated by Django 2.2.3 on 2019-07-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_movie_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='movie',
            table='douban_movie',
        ),
    ]
