# Generated by Django 2.2.3 on 2019-07-22 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190722_1218'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doubanmovie',
            table=None,
        ),
    ]
