# Generated by Django 2.2.3 on 2019-07-22 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20190722_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doubanmovie',
            options={'managed': True},
        ),
    ]
