# Generated by Django 2.2.3 on 2019-07-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190722_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubanmovie',
            name='detail_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='doubanmovie',
            name='img_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='doubanmovie',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
